apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  namespace: airflow-app
  labels:
    xccelerated.io/moritz-project: airflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-app
  template:
    metadata:
      labels:
        app: airflow-app
    spec:
      containers:
        - name: airflow-scheduler 
          image: 'apache/airflow:2.2.4' 
          imagePullPolicy: IfNotPresent
          args: ['scheduler']
          volumeMounts: 
            - name: shared
              mountPath: /dags/
          env:
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /dags
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
              valueFrom: 
                configMapKeyRef: 
                  name: airflow-config 
                  key: sql_alchemy_conn 
        - name: airflow-webserver 
          image: 'apache/airflow:2.2.4' 
          imagePullPolicy: IfNotPresent 
          ports: 
            - containerPort: 8090 
          args: ['webserver', '-p', '8090']
          volumeMounts: 
            - name: shared
              mountPath: /dags/
          env:
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /dags
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
              valueFrom: 
                configMapKeyRef: 
                  name: airflow-config 
                  key: sql_alchemy_conn 
      initContainers:
        - name: airflow-create-user
          image: apache/airflow:2.2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
              valueFrom: 
                configMapKeyRef: 
                  name: airflow-config
                  key: sql_alchemy_conn
          command: ["airflow"]
          args: ["users", "create", "-e", "airflow@airflow.com", "-f", "airflow", "-l", "airflow", "-p", "airflow", "-r", "Admin", "-u", "airflow"]
      volumes:
        - name: shared
          hostPath: 
            path: /dags
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-ui-service
  namespace: airflow-app
  labels:
    xccelerated.io/moritz-project: airflow-app
spec:
  selector:
    app: airflow-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
